[[headers]]
  for = "/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = ["https://geeks4life.netlify.app", "https://testingbackend.netlify.app"]
    Access-Control-Allow-Headers = ["Content-Type"]
    Access-Control-Allow-Methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]

[[redirects]]
  force = true
  from = "/functions/server/*"
  status = 200
  to = "/.netlify/functions/server/:splat"