[build]
  command = "node server.js"
  publish = "barbershop_web/barbershop_web"
  functions = "barbershop_web/barbershop_web/functions"



[[redirects]]
  from = "/functions/server/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true