[build]
  command = "node barbershop_web/server.js"
  publish = "barbershop_web"
  functions = "barbershop_web/functions"





[[redirects]]
  from = "/functions/server/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true