[build]
  base = "barbershop_web"
  command = "node server.js"
  publish = "/"
  functions = "barbershop_web/functions"

[[redirects]]
  force = true
  from = "/functions/server/*"
  status = 200
  to = "/.netlify/functions/server/:splat"