[build]
  command = "npm run build"
  publish = "barbershop_web/build"
  functions = "barbershop_web/functions"

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = ["*"]
    Access-Control-Allow-Headers = ["Content-Type"]
    Access-Control-Allow-Methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]

[functions]
  directory = "barbershop_web/functions"  # Updated to the correct functions directory
